### PR TITLE
Add queen-attack

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Comment by axtens** [comment]
Could a [type](https://openeuphoria.org/docs/lang_decl.html#_117_types) be used/ demonstrated?

**Comment by axtens** [comment]
What you've got is perfectly okay. The boundaries for the queen seemed like a use case for a user-defined type

**Comment by BNAndras** [comment]
I'll have to play with it this weekend, but if we do go that way, I'll want to add an instructions append. It doesn't have to be anything special as long as it makes it clear we're using a custom type rather than the built-in types from the other exercises.

**Comment by BNAndras** [comment]
Merge conflict fixed

**Review by axtens — APPROVED** [review]

**Pull request merged**
